language: generic

services:
  - docker

env:
  global:
    - GIT_REMOTE=$(git remote get-url origin)

before_install:
  - curl -s https://s3-api.us-geo.objectstorage.softlayer.net/armada-config/build-tools/build-tools.tar.gz |tar -xvz
  - ./build-tools/install.sh
  - npm install -g mustache htmllint

script:
  - htmllint html/*.html
  - docker build --pull --rm -t "mckaymic/razeedemo:${TRAVIS_COMMIT}" .
  - docker images
  - mkdir -p "/tmp/razeedemo"
  - ./build/process-template.sh kubernetes/razeedemo/resource.yaml >/tmp/razeedemo/resource.yaml
  - ls -l /tmp/razeedemo

before_deploy:
  - docker login -u="${DOCKER_ID}" -p="${DOCKER_PASSWORD}"

deploy:
  - provider: script
    script: build/publish-razeedemo.sh
    skip_cleanup: true
    on:
      branch: master
