apiVersion: v1
kind: List
metadata:
  name: razeedemo
  namespace: default
  annotations:
    version: "{{TRAVIS_COMMIT}}"
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        version: "{{TRAVIS_COMMIT}}"
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
      name: razeedemo
      namespace: default
    spec:
      replicas: 1
      revisionHistoryLimit: 0
      selector:
        matchLabels:
          app: razeedemo
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: razeedemo
          name: razeedemo
        spec:
          containers:
          - image: "mckaymic/razeedemo:{{TRAVIS_COMMIT}}"
            imagePullPolicy: Always
            name: razeedemo
            ports:
            - containerPort: 80
              protocol: TCP
